server:
  port: ${PORT:10000}  # Render asigna el puerto dinámicamente

spring:
  application:
    name: transfers-api
  
  # Base de datos PostgreSQL de Render (URL dinámica)
  r2dbc:
    url:  r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:transfers_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Maldonado12478910}
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
  
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    com.example.transfers: INFO
    io.r2dbc.postgresql: INFO