server:
  port: ${PORT:10000}

spring:
  application:
    name: transfers-api
  
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/transfers_db}
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
  
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    com.example.transfers: INFO
    io.r2dbc.postgresql: INFO