spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}  # Usa perfil según variable de entorno

server:
  port: ${PORT:8080}

# Configuración por defecto (desarrollo local)
---
spring:
  config:
    activate:
      on-profile: default
  
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/transfers_db
    username: postgres
    password: Maldonado12478910
    pool:
      initial-size: 10
      max-size: 20

  sql:
    init:
      mode: always

logging:
  level:
    io.r2dbc.postgresql: DEBUG
    com.example.transfers: DEBUG